// Mapa id → nombre oficial en inglés (Monster Manual 2024).
// Se usa en runtime para la búsqueda y también para inyectarlo al JSON legacy.
export const NOMBRES_INGLES = {
  goblin: 'Goblin', lobo_terrible: 'Dire Wolf', orco: 'Orc', arpia: 'Harpy', espectro: 'Specter',
  mimico: 'Mimic', cubo_gelatinoso: 'Gelatinous Cube', gigante_colinas: 'Hill Giant', contemplador: 'Beholder',
  liche: 'Lich', aboleth: 'Aboleth', acechador_invisible: 'Invisible Stalker', osgo_acechador: 'Stalker Ogre',
  aarakocra_aeromante: 'Aarakocra Aeromancer', aguila: 'Eagle', aguila_gigante: 'Giant Eagle', alce: 'Elk',
  alce_gigante: 'Giant Elk', alfombra_asfixiante_animada: 'Animated Smothering Carpet', alosaurio: 'Allosaurus',
  amasijo_de_aniquilacion: 'Blob of Annihilation', ankheg: 'Ankheg', aarakocra: 'Aarakocra',
  aarakocra_escaramuzador: 'Aarakocra Skirmisher', elemental_del_aire: 'Air Elemental', animal_lord: 'Animal Lord',
  objetos_animados: 'Animated Objects', armadura_animada: 'Animated Armor', escoba_animada: 'Animated Broom',
  espadavoladoraanimada: 'Flying Sword', anquilosaurio: 'Ankylosaurus', simio: 'Ape', arcanaloth: 'Arcanaloth',
  archelon: 'Archelon', arch_hag: 'Arch-Hag', asesino: 'Assassin', plantas_despiertas: 'Awakened Plants',
  arbusto_despierto: 'Awakened Shrub', arbol_despierto: 'Awakened Tree', picosdehacha: 'Axe Beaks', azers: 'Azer',
  babuino: 'Baboon', 'tejón': 'Badger', balor: 'Balor', bandidos: 'Bandits', banshee: 'Banshee',
  diablo_barbado: 'Barbed Devil', barlgura: 'Barlgura', basilisco: 'Basilisk', murcielago: 'Bat',
  diablo_barbudo: 'Bearded Devil', behir: 'Behir', beholder: 'Beholder', berserkers: 'Berserkers',
  oso_negro: 'Black Bear', dragones_negros: 'Black Dragons', budin_negro: 'Black Pudding', blights: 'Blights',
  perro_parlante: 'Blink Dog', gota_aniquilacion: 'Drop of Annihilation', halcon_sangriento: 'Blood Hawk',
  dragones_azules: 'Blue Dragons', jabali: 'Boar', diablo_oseo: 'Bone Devil', naga_osea: 'Bone Naga',
  dragonesdebronce: 'Brass Dragons', dragonesdecobre: 'Copper Dragons', oso_pardo: 'Brown Bear', bugbears: 'Bugbears',
  bulettes: 'Bulettes', bullywugs: 'Bullywugs', cambion: 'Cambion', camello: 'Camel', reptador_carroñero: 'Carrion Crawler',
  gato: 'Cat', centauros: 'Centaurs', diablo_cadenas: 'Chain Devil', chasme: 'Chasme', quimera: 'Chimera', chuul: 'Chuul',
  golemdearcilla: 'Clay Golem', cloaker: 'Cloaker', gigante_nubes: 'Cloud Giant', cockatrices: 'Cockatrices',
  coloso: 'Colossus', plebeyo: 'Commoner', serpiente_constrictora: 'Constrictor Snake', couatl: 'Couatl', cangrejo: 'Crab',
  manos_reptantes: 'Crawling Hands', cocodrilo: 'Crocodile', cultistas: 'Cultists', ciclopes: 'Cyclopes', dao: 'Dao',
  manto_oscuro: 'Darkmantle', perro_de_la_muerte: 'Death Dog', death_knights: 'Death Knights', tirano_de_la_muerte: 'Death Tyrant',
  ciervo: 'Deer', semiliche: 'Demilich', deva: 'Deva', bestia_desplazante: 'Displacer Beast', djinni: 'Djinni',
  doppelganger: 'Doppelganger', dracolich: 'Dracolich', caballo_de_tiro: 'Draft Horse', dragon_tortuga: 'Dragon Turtle',
  dretches: 'Dretches', drider: 'Drider', druida: 'Druid', driade: 'Dryad', elemental_de_tierra: 'Earth Elemental',
  efreeti: 'Efreeti', cataclismo_elemental: 'Elemental Cataclysm', elefante: 'Elephant', empireos: 'Empyreans',
  calavera_de_fuego: 'Flameskull', golem_de_carne: 'Flesh Golem', flumph: 'Flumph', serpiente_voladora: 'Flying Snake',
  fomorian: 'Fomorian', rana: 'Frog', gigante_de_hielo: 'Frost Giant', fungi: 'Fungi', galeb_duhr: 'Galeb Duhr',
  gargola: 'Gargoyle', ghasts: 'Ghasts', fantasma: 'Ghost', ghouls: 'Ghouls', simio_gigante: 'Giant Ape',
  tejon_gigante: 'Giant Badger', murcielago_gigante: 'Giant Bat', jabali_gigante: 'Giant Boar', ciempies_gigante: 'Giant Centipede',
  serpiente_constrictora_gigante: 'Giant Constrictor Snake', cangrejo_gigante: 'Giant Crab', cocodrilo_gigante: 'Giant Crocodile',
  escarabajo_de_fuego_gigante: 'Giant Fire Beetle', rana_gigante: 'Giant Frog', cabra_gigante: 'Giant Goat',
  hiena_gigante: 'Giant Hyena', lagarto_gigante: 'Giant Lizard', pulpo_gigante: 'Giant Octopus', buho_gigante: 'Giant Owl',
  rata_gigante: 'Giant Rat', caballito_de_mar_gigante: 'Giant Sea Horse', escorpion_gigante: 'Giant Scorpion',
  tiburon_gigante: 'Giant Shark', arana_gigante: 'Giant Spider', calamar_gigante: 'Giant Squid', sapo_gigante: 'Giant Toad',
  githyanki: 'Githyanki', githzerai: 'Githzerai', glabrezu: 'Glabrezu', gladiador: 'Gladiator', gnolls: 'Gnolls',
  cabra: 'Goat', dragones_dorados: 'Gold Dragons', gorgonas: 'Gorgons', goristro: 'Goristro', limos_grises: 'Gray Oozes',
  bruja_verde: 'Green Hag', grell: 'Grell', gricks: 'Gricks', grifo: 'Griffon', grimlock: 'Grimlock',
  naga_guardiana: 'Guardian Naga', guardias: 'Guards', medio_dragon: 'Half-Dragon', halcon: 'Hawk', perro_infernal: 'Hell Hound',
  horror_acorazado: 'Helmed Horror', dragones_verdes: 'Green Dragons', hezrou: 'Hezrou', hipogrifo: 'Hippogriff',
  hipopotamo: 'Hippopotamus', hobgoblins: 'Hobgoblins', homunculus: 'Homunculus', hook_horror: 'Hook Horror',
  horned_devil: 'Horned Devil', hunter_shark: 'Hunter Shark', hidra: 'Hydra', hiena: 'Hyena', diablo_de_hielo: 'Ice Devil',
  diablillo: 'Imp', incubo: 'Incubus', devorador_de_intelectos: 'Intellect Devourer', golem_de_hierro: 'Iron Golem',
  chacal: 'Jackal', chacalwere: 'Jackalwere', kenku: 'Kenku', orca: 'Orca', caballeros: 'Knights', kobolds: 'Kobolds',
  kraken: 'Kraken', kuo_toa: 'Kuo-toa', lamia: 'Lamia', larvas: 'Larvae', lemures: 'Lemures', leon: 'Lion',
  lagarto: 'Lizard', hombres_lagarto: 'Lizardfolk', magos: 'Mages', magmin: 'Magmin', mamut: 'Mammoth', manes: 'Manes',
  manticoa: 'Manticore', marid: 'Marid', marilith: 'Marilith', mastin: 'Mastiff', medusa: 'Medusa', mefits: 'Mephits',
  merfolk: 'Merfolk', merrow: 'Merrow', mezzoloth: 'Mezzoloth', mind_flayers: 'Mind Flayers',
  minotauro_de_baphomet: 'Minotaur of Baphomet', modrones: 'Modrones', mula: 'Mule', momias: 'Mummies',
  'micónidos': 'Myconids', nalfeshnee: 'Nalfeshnee', bruja_nocturna: 'Night Hag', pesadilla: 'Nightmare', nobles: 'Nobles',
  nothic: 'Nothic', nycaloth: 'Nycaloth', gelatina_ocre: 'Ochre Jelly', pulpo: 'Octopus', ogros: 'Ogres', oni: 'Oni',
  otyugh: 'Otyugh', buho: 'Owl', osos_buho: 'Owlbears', pantera: 'Panther', pegaso: 'Pegasus', artistas: 'Performers',
  periton: 'Peryton', arana_fase: 'Phase Spider', perforador: 'Piercer', piranhas: 'Piranhas', piratas: 'Pirates',
  diablo_del_foso: 'Pit Fiend', pixies: 'Pixies', planetar: 'Planetar', plesiosaurio: 'Plesiosaurus', oso_polar: 'Polar Bear',
  poltergeist: 'Poltergeist', poni: 'Pony', sacerdotes: 'Priests', pseudodragon: 'Pseudodragon', pteranodon: 'Pteranodon',
  gusano_purpura: 'Purple Worm', quaggoths: 'Quaggoths', quasit: 'Quasit', rakshasa: 'Rakshasa', rata: 'Rat',
  cuervo: 'Raven', dragones_rojos: 'Red Dragons', tiburon_de_arrecife: 'Reef Shark', remorhazes: 'Remorhazes',
  revenants: 'Revenants', rinoceronte: 'Rhinoceros', caballo_de_montar: 'Riding Horse', roc: 'Roc', roper: 'Roper',
  monstruo_oxidante: 'Rust Monster', tigre_dientes_de_sable: 'Saber-Toothed Tiger', sahuagin: 'Sahuagin',
  salamanders: 'Salamanders', satyrs: 'Satyrs', espantapajaros: 'Scarecrow', escorpion: 'Scorpion', exploradores: 'Scouts',
  bruja_marina: 'Sea Hag', caballito_de_mar: 'Sea Horse', sombra: 'Shadow', demonio_de_sombra: 'Shadow Demon',
  dragones_de_sombra: 'Shadow Dragons', monticulo_hambriento: 'Shambling Mound', guardian_de_escudo: 'Shield Guardian',
  dragones_plateados: 'Silver Dragons', esqueletos: 'Skeletons', slaadi: 'Slaadi', solar: 'Solar', espectador: 'Spectator',
  esfinges: 'Sphinxes', arana: 'Spider', sprite: 'Sprite', stirges: 'Stirges', gigante_de_piedra: 'Stone Giant',
  gigante_de_la_tormenta: 'Storm Giant', sucuubo: 'Succubus', enjambre_de_murcielagos: 'Swarm of Bats',
  enjambre_de_insectos: 'Swarm of Insects', enjambre_de_ratas: 'Swarm of Rats', enjambre_de_cuervos: 'Swarm of Ravens',
  enjambre_de_serpientes_venenosas: 'Swarm of Poisonous Snakes', tarrasque: 'Tarrasque', matones: 'Thugs', ents: 'Treants',
  trolls: 'Trolls', unicornios: 'Unicorns', vampiros: 'Vampires', hombre_rata: 'Wererat', hombre_lobo: 'Werewolf',
  tumularios: 'Wights', fuego_fatuo: 'Will-o\'-Wisp', wyvern: 'Wyvern', xorn: 'Xorn', yeti: 'Yeti', yuan_ti: 'Yuan-ti',
  zombis: 'Zombies', dragones_hada: 'Faerie Dragons'
};